/**
 * Chatbot message roles.
 * - `user`: Message authored by the end user.
 * - `assistant`: Response generated by the AgentCore AI assistant.
 */
export type MessageRole = 'user' | 'assistant';

/**
 * State of an individual message in a conversation.
 * - `done`: Message generation is complete.
 * - `thinking`: Assistant is currently processing the prompt.
 * - `streaming`: Assistant response is streaming.
 * - `stopped`: Assistant generation was aborted by the user.
 */
export type MessageState = 'done' | 'thinking' | 'streaming' | 'stopped';

/**
 * Metadata for a file/image attachment persisted in storage.
 */
export type StoredAttachment = {
  /** Unique identifier for this attachment. */
  id: string;
  /** Original filename. */
  name: string;
  /** Image format extension (e.g., 'png', 'jpeg', 'webp'). */
  format: string;
  /** MIME media type (e.g., 'image/png'). */
  mediaType: string;
  /** File size in bytes. */
  size: number;
};

/**
 * Image attachment currently queued or uploaded during the active session,
 * containing binary base64 data for API payload and object URL for preview rendering.
 */
export type PendingUpload = StoredAttachment & {
  /** Base64-encoded file payload (excluding data URL prefix). */
  bytesBase64: string;
  /** Local object URL for rendering thumbnail in the UI. */
  previewUrl: string;
};

/**
 * A single chat message in a conversation thread.
 */
export type ChatMessage = {
  /** Unique message identifier. */
  id: string;
  /** Role of the message author ('user' | 'assistant'). */
  role: MessageRole;
  /** Plaintext / markdown content of the message. */
  content: string;
  /** Original user prompt text (optional). */
  inputText?: string;
  /** Image attachments associated with this message. */
  attachments?: StoredAttachment[];
  /** Timestamp when the message was created (milliseconds since epoch). */
  createdAt: number;
  /** Lifecycle state of the message. */
  state: MessageState;
  /** Flag indicating whether the response was generated locally as a fallback. */
  usedMock?: boolean;
  /** Identifier of the user message this assistant message is answering. */
  replyToUserId?: string;
};

/**
 * A conversation session containing a sequence of messages.
 */
export type ChatThread = {
  /** Unique session identifier (passed as runtime sessionId to AgentCore). */
  id: string;
  /** User identifier owning this thread. */
  userId: string;
  /** Display title for the conversation in the sidebar. */
  title: string;
  /** Timestamp when the conversation was initiated. */
  createdAt: number;
  /** Timestamp of the most recent message or update. */
  updatedAt: number;
  /** Map of user message ID to selected assistant message variant ID. */
  variantSelections: Record<string, string>;
  /** Array of messages in chronological order. */
  messages: ChatMessage[];
};

/**
 * Root state for the chatbot data layer.
 */
export type ChatState = {
  /** Optional custom HTTP fallback endpoint URL. */
  endpoint: string;
  /** Active user ID associated with this chat session. */
  userId: string;
  /** List of all conversation threads for this user. */
  threads: ChatThread[];
  /** ID of the currently selected/active conversation thread. */
  activeThreadId: string;
};

/**
 * Layout and visibility state for the chatbot drawer UI.
 */
export type UiState = {
  /** Whether the sliding drawer is open. */
  drawerOpen: boolean;
  /** Whether the conversation list sidebar is collapsed. */
  conversationsCollapsed: boolean;
  /** Width of the full drawer in pixels. */
  panelWidth: number;
  /** Width of the conversation sidebar in pixels. */
  conversationPaneWidth: number;
};

/**
 * Assistant connection and operational status indicators.
 * - `idle`: Ready for user input.
 * - `online`: Successfully connected to AgentCore.
 * - `busy`: Processing request or awaiting response.
 * - `error`: Error occurred during generation or invoke.
 */
export type StatusMode = 'idle' | 'online' | 'busy' | 'error';

/**
 * Active in-flight request tracking for cancellation.
 */
export type InflightRequest = {
  /** AbortController used to cancel the in-flight request. */
  controller: AbortController;
  /** Target thread ID of the active generation. */
  threadId: string;
  /** Message ID of the assistant response being populated. */
  msgId: string;
};
